# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ETCQDG
                                 A QGIS plugin
 CQDG
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-04-02
        copyright            : (C) 2022 by CQDG
        email                : CQDG
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'CQDG'
__date__ = '2022-04-02'
__copyright__ = '(C) 2022 by CQDG'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ETCQDG class from file ETCQDG.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .CQDG import ETCQDGPlugin
    return ETCQDGPlugin()
