# -*- coding: utf-8 -*-

"""
/***************************************************************************
 ETCQDG
                                 A QGIS plugin
 QPEC
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-04-02
        copyright            : (C) 2022 by Elias Naim
        email                : elias_naim2008@hotmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Elias Nasr Naim Elias'
__date__ = '2022-04-02'
__copyright__ = '(C) 2022 by Elias Nasr Naim Elias'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.core import QgsProcessing
from qgis.core import QgsProcessingAlgorithm
from qgis.core import QgsProcessingMultiStepFeedback
from qgis.core import QgsProcessingParameterVectorLayer
from qgis.core import QgsProcessingParameterField
from qgis.core import QgsProcessingParameterNumber
from qgis.core import QgsProcessingParameterBoolean
from qgis.core import QgsProcessingParameterFeatureSink
from qgis.core import QgsProcessingParameterRasterDestination
from qgis.core import QgsExpression
import processing


from qgis.core import QgsApplication

import os

profilepath = QgsApplication.qgisSettingsDirPath()


class ETCQDGAlgorithm(QgsProcessingAlgorithm):

    def initAlgorithm(self, config=None):
        self.addParameter(QgsProcessingParameterVectorLayer('entrecomosdadosdereferncia', 'Insira as feições de Referência (Camada 1)', types=[QgsProcessing.TypeVectorPoint], defaultValue=None))
        self.addParameter(QgsProcessingParameterField('teste', 'Atributo da Camada 1', type=QgsProcessingParameterField.Any, parentLayerParameterName='entrecomosdadosdereferncia', allowMultiple=False, defaultValue=None))
        self.addParameter(QgsProcessingParameterVectorLayer('entrecomosdadosaseremavaliados', 'Insira as feições a serem avaliadas (Camada 2)', types=[QgsProcessing.TypeVectorPoint], defaultValue=None))
        self.addParameter(QgsProcessingParameterField('selecioneocampodacamada2', 'Atributo da Camada 2', type=QgsProcessingParameterField.Any, parentLayerParameterName='entrecomosdadosaseremavaliados', allowMultiple=False, defaultValue=None))
        self.addParameter(QgsProcessingParameterNumber('EntrecomodenominadordeEscaladesejado', 'Insira o denominador de Escala desejado', type=QgsProcessingParameterNumber.Double, minValue=0, maxValue=1e+09, defaultValue=1000))
        self.addParameter(QgsProcessingParameterBoolean('exibirresultadoparatodasasescalasdomsb', 'Exibir resultado para todas as Escalas do MSB', optional=True, defaultValue=False))
        self.addParameter(QgsProcessingParameterFeatureSink('Resultado', 'Resultado', type=QgsProcessing.TypeVectorAnyGeometry, createByDefault=True, supportsAppend=True, defaultValue=None))

    def processAlgorithm(self, parameters, context, model_feedback):
        # Use a multi-step feedback, so that individual child algorithm progress reports are adjusted for the
        # overall progress through the model
        feedback = QgsProcessingMultiStepFeedback(23, model_feedback)
        results = {}
        outputs = {}

        # Coordenada E (aval)
        alg_params = {
            'FIELD_LENGTH': 10,
            'FIELD_NAME': 'E_aval',
            'FIELD_PRECISION': 3,
            'FIELD_TYPE': 0,  # Float
            'FORMULA': '$x',
            'INPUT': parameters['entrecomosdadosaseremavaliados'],
            'NEW_FIELD': True,
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['CoordenadaEAval'] = processing.run('qgis:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(1)
        if feedback.isCanceled():
            return {}

        # Coordenada N (aval)
        alg_params = {
            'FIELD_LENGTH': 10,
            'FIELD_NAME': 'N_aval',
            'FIELD_PRECISION': 3,
            'FIELD_TYPE': 0,  # Float
            'FORMULA': '$y',
            'INPUT': outputs['CoordenadaEAval']['OUTPUT'],
            'NEW_FIELD': True,
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['CoordenadaNAval'] = processing.run('qgis:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(2)
        if feedback.isCanceled():
            return {}

        # Coordenada E (ref)
        alg_params = {
            'FIELD_LENGTH': 10,
            'FIELD_NAME': 'E_ref',
            'FIELD_PRECISION': 3,
            'FIELD_TYPE': 0,  # Float
            'FORMULA': '$x',
            'INPUT': parameters['entrecomosdadosdereferncia'],
            'NEW_FIELD': True,
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['CoordenadaERef'] = processing.run('qgis:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(3)
        if feedback.isCanceled():
            return {}

        # Coordenada N (ref)
        alg_params = {
            'FIELD_LENGTH': 10,
            'FIELD_NAME': 'N_ref',
            'FIELD_PRECISION': 3,
            'FIELD_TYPE': 0,  # Float
            'FORMULA': '$y',
            'INPUT': outputs['CoordenadaERef']['OUTPUT'],
            'NEW_FIELD': True,
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['CoordenadaNRef'] = processing.run('qgis:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(4)
        if feedback.isCanceled():
            return {}

        # Join_Dados
        alg_params = {
            'DISCARD_NONMATCHING': False,
            'FIELD': parameters['teste'],
            'FIELDS_TO_COPY': [''],
            'FIELD_2': parameters['selecioneocampodacamada2'],
            'INPUT': outputs['CoordenadaNRef']['OUTPUT'],
            'INPUT_2': outputs['CoordenadaNAval']['OUTPUT'],
            'METHOD': 1,  # Tomar atributos apenas da primeira feição coincidente (uma-por-uma)
            'PREFIX': '',
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['Join_dados'] = processing.run('native:joinattributestable', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(5)
        if feedback.isCanceled():
            return {}

        # ID
        alg_params = {
            'FIELD_LENGTH': 10,
            'FIELD_NAME': 'ID',
            'FIELD_PRECISION': 10,
            'FIELD_TYPE': 1,  # Número inteiro
            'FORMULA': '$id',
            'INPUT': outputs['Join_dados']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['Id'] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(6)
        if feedback.isCanceled():
            return {}

        # Distância Euclidiana
        alg_params = {
            'FIELD_LENGTH': 10,
            'FIELD_NAME': 'DE',
            'FIELD_PRECISION': 6,
            'FIELD_TYPE': 0,  # Float
            'FORMULA': 'sqrt((( \"E_aval\" - \"E_ref\" )^\'2\')+(( \"N_aval\" - \"N_ref\")^\'2\'))',
            'INPUT': outputs['Id']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['DistnciaEuclidiana'] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(7)
        if feedback.isCanceled():
            return {}

        # RMS
        alg_params = {
            'FIELD_LENGTH': 10,
            'FIELD_NAME': 'RMS',
            'FIELD_PRECISION': 3,
            'FIELD_TYPE': 0,  # Float
            'FORMULA': 'sqrt(sum(\"DE\"^2)/count(\"ID\"))',
            'INPUT': outputs['DistnciaEuclidiana']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['Rms'] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(8)
        if feedback.isCanceled():
            return {}

        # 1:1000
        alg_params = {
            'FIELD_LENGTH': 10,
            'FIELD_NAME': '1:1000',
            'FIELD_PRECISION': 3,
            'FIELD_TYPE': 2,  # String
            'FORMULA': 'CASE WHEN sum(\"DE\"<=0.28) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=0.17\r\nTHEN \'Classe A\'\r\nWHEN sum(\"DE\"<=0.50) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=0.30\r\nTHEN \'Classe B\'\r\nWHEN sum(\"DE\"<=0.80) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=0.50\r\nTHEN \'Classe C\'\r\nWHEN sum(\"DE\"<=1.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=0.60\r\nTHEN \'Classe D\' ELSE \'Rejeitado\'\r\nEND',
            'INPUT': outputs['Rms']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs[''] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(9)
        if feedback.isCanceled():
            return {}

        # 1:2000
        alg_params = {
            'FIELD_LENGTH': 10,
            'FIELD_NAME': '1:2000',
            'FIELD_PRECISION': 3,
            'FIELD_TYPE': 2,  # String
            'FORMULA': 'CASE WHEN sum(\"DE\"<=0.56) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=0.34\r\nTHEN \'Classe A\'\r\nWHEN sum(\"DE\"<=1.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=0.60\r\nTHEN \'Classe B\'\r\nWHEN sum(\"DE\"<=1.6) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=1.0\r\nTHEN \'Classe C\'\r\nWHEN sum(\"DE\"<=2.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=1.2\r\nTHEN \'Classe D\' ELSE \'Rejeitado\' END',
            'INPUT': outputs['']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs[''] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(10)
        if feedback.isCanceled():
            return {}

        # 1:5000
        alg_params = {
            'FIELD_LENGTH': 10,
            'FIELD_NAME': '1:5000',
            'FIELD_PRECISION': 3,
            'FIELD_TYPE': 2,  # String
            'FORMULA': 'CASE WHEN sum(\"DE\"<=1.4) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=0.85\r\nTHEN \'Classe A\'\r\nWHEN sum(\"DE\"<=2.5) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=1.5\r\nTHEN \'Classe B\'\r\nWHEN sum(\"DE\"<=4.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=2.5\r\nTHEN \'Classe C\'\r\nWHEN sum(\"DE\"<=5.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=3\r\nTHEN \'Classe D\'\r\nELSE \'Rejeitado\' END',
            'INPUT': outputs['']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs[''] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(11)
        if feedback.isCanceled():
            return {}

        # 1:10000
        alg_params = {
            'FIELD_LENGTH': 10,
            'FIELD_NAME': '1:10000',
            'FIELD_PRECISION': 3,
            'FIELD_TYPE': 2,  # String
            'FORMULA': 'CASE WHEN sum(\"DE\"<=2.8) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=1.7\r\nTHEN \'Classe A\'\r\nWHEN sum(\"DE\"<=5.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=3.0\r\nTHEN \'Classe B\'\r\nWHEN sum(\"DE\"<=8.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=5.0\r\nTHEN \'Classe C\'\r\nWHEN sum(\"DE\"<=10.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=6.0\r\nTHEN \'Classe D\'\r\nELSE \'Rejeitado\' END',
            'INPUT': outputs['']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs[''] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(12)
        if feedback.isCanceled():
            return {}

        # 1:25000
        alg_params = {
            'FIELD_LENGTH': 10,
            'FIELD_NAME': '1:25000',
            'FIELD_PRECISION': 3,
            'FIELD_TYPE': 2,  # String
            'FORMULA': 'CASE WHEN sum(\"DE\"<=7.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=4.25\r\nTHEN \'Classe A\'\r\nWHEN sum(\"DE\"<=12.50) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=7.5\r\nTHEN \'Classe B\'\r\nWHEN sum(\"DE\"<=20.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=12.5\r\nTHEN \'Classe C\'\r\nWHEN sum(\"DE\"<=25.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=15.0\r\nTHEN \'Classe D\' ELSE \'Rejeitado\'\r\nEND',
            'INPUT': outputs['']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs[''] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(13)
        if feedback.isCanceled():
            return {}

        # 1:50000
        alg_params = {
            'FIELD_LENGTH': 10,
            'FIELD_NAME': '1:50000',
            'FIELD_PRECISION': 3,
            'FIELD_TYPE': 2,  # String
            'FORMULA': 'CASE WHEN sum(\"DE\"<=14.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=8.51\r\nTHEN \'Classe A\'\r\nWHEN sum(\"DE\"<=25.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=15.0\r\nTHEN \'Classe B\'\r\nWHEN sum(\"DE\"<=40.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=25.0\r\nTHEN \'Classe C\'\r\nWHEN sum(\"DE\"<=50.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=30.0\r\nTHEN \'Classe D\'\r\nELSE \'Rejeitado\' END',
            'INPUT': outputs['']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs[''] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(14)
        if feedback.isCanceled():
            return {}

        # 1:100000
        alg_params = {
            'FIELD_LENGTH': 10,
            'FIELD_NAME': '1:100000',
            'FIELD_PRECISION': 3,
            'FIELD_TYPE': 2,  # String
            'FORMULA': 'CASE WHEN sum(\"DE\"<=28.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=17.02\r\nTHEN \'Classe A\'\r\nWHEN sum(\"DE\"<=50.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=30.0\r\nTHEN \'Classe B\'\r\nWHEN sum(\"DE\"<=80.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=50.0\r\nTHEN \'Classe C\'\r\nWHEN sum(\"DE\"<=100.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=60.0\r\nTHEN \'Classe D\' ELSE \'Rejeitado\'\r\nEND',
            'INPUT': outputs['']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs[''] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(15)
        if feedback.isCanceled():
            return {}

        # 1:250000
        alg_params = {
            'FIELD_LENGTH': 10,
            'FIELD_NAME': '1:250000',
            'FIELD_PRECISION': 3,
            'FIELD_TYPE': 2,  # String
            'FORMULA': 'CASE WHEN sum(\"DE\"<=70.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=42.55\r\nTHEN \'Classe A\'\r\nWHEN sum(\"DE\"<=125.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=75.0\r\nTHEN \'Classe B\'\r\nWHEN sum(\"DE\"<=200.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=125.0\r\nTHEN \'Classe C\'\r\nWHEN sum(\"DE\"<=250.0) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=150.0\r\nTHEN \'Classe D\' ELSE \'Rejeitado\'\r\nEND\r\n',
            'INPUT': outputs['']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs[''] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(16)
        if feedback.isCanceled():
            return {}

        # Escala
        alg_params = {
            'FIELD_LENGTH': 10,
            'FIELD_NAME': 'va',
            'FIELD_PRECISION': 10,
            'FIELD_TYPE': 0,  # Float
            'FORMULA': parameters['EntrecomodenominadordeEscaladesejado'],
            'INPUT': outputs['']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['Escala'] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(17)
        if feedback.isCanceled():
            return {}

        # Classe_A
        alg_params = {
            'FIELD_LENGTH': 50,
            'FIELD_NAME': 'Classe_A',
            'FIELD_PRECISION': 10,
            'FIELD_TYPE': 2,  # String
            'FORMULA': 'CASE WHEN sum(\"DE\"<=0.28*\"va\"/1000) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=0.17*\"va\"/1000\r\nTHEN \'Aceito\'\r\nELSE \'Rejeitado\'\r\nEND',
            'INPUT': outputs['Escala']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['Classe_a'] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(18)
        if feedback.isCanceled():
            return {}

        # Classe_B
        alg_params = {
            'FIELD_LENGTH': 50,
            'FIELD_NAME': 'Classe_B',
            'FIELD_PRECISION': 0,
            'FIELD_TYPE': 2,  # String
            'FORMULA': 'CASE WHEN sum(\"DE\"<=0.50*\"va\"/1000) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=0.30*\"va\"/1000\r\nTHEN \'Aceito\'\r\nELSE \'Rejeitado\'\r\nEND',
            'INPUT': outputs['Classe_a']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['Classe_b'] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(19)
        if feedback.isCanceled():
            return {}

        # Classe_C
        alg_params = {
            'FIELD_LENGTH': 50,
            'FIELD_NAME': 'Classe_C',
            'FIELD_PRECISION': 0,
            'FIELD_TYPE': 2,  # String
            'FORMULA': 'CASE WHEN sum(\"DE\"<=0.80*\"va\"/1000) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=0.50*\"va\"/1000\r\nTHEN \'Aceito\'\r\nELSE \'Rejeitado\'\r\nEND',
            'INPUT': outputs['Classe_b']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['Classe_c'] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(20)
        if feedback.isCanceled():
            return {}

        # Classe_D
        alg_params = {
            'FIELD_LENGTH': 50,
            'FIELD_NAME': 'Classe_D',
            'FIELD_PRECISION': 0,
            'FIELD_TYPE': 2,  # String
            'FORMULA': 'CASE WHEN sum(\"DE\"<=1.0*\"va\"/1000) >= 0.9*count(\"ID\") AND sqrt(sum(\"DE\"^2)/count(\"ID\"))<=0.60*\"va\"/1000\r\nTHEN \'Aceito\'\r\nELSE \'Rejeitado\'\r\nEND',
            'INPUT': outputs['Classe_c']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['Classe_d'] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(21)
        if feedback.isCanceled():
            return {}
            
        # Quartil2
        alg_params = {
            'FIELD_LENGTH': 10,
            'FIELD_NAME': 'Quartil2',
            'FIELD_PRECISION': 3,
            'FIELD_TYPE': 0,  # Decimal (double)
            'FORMULA': 'CASE WHEN "DE" <= q1("DE") then \'1\'\r\n\r\nWHEN "DE" > q1("DE") and"DE" <= median("DE") then \'2\'\r\n\r\nWHEN "DE" > median("DE") and "DE" <= q3("DE") then \'3\'\r\n\r\nWHEN "DE" > q3("DE")  then \'4\'\r\n\r\nEND',
            'INPUT': outputs['Classe_d']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['Quartil2'] = processing.run('native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        
        feedback.setCurrentStep(22)
        if feedback.isCanceled():
            return {}

        # Retain fields
        
        aval = self.parameterAsBool(parameters, "exibirresultadoparatodasasescalasdomsb", context)
        
        if aval == True:
            
            alg_params = {
                'FIELDS': ["'",'ID','DE','RMS','1:1000','1:2000', '1:5000', '1:10000', '1:25000', '1:50000', '1:100000', '1:250000','Quartil2',"'"],
                'INPUT': outputs['Quartil2']['OUTPUT'],
                'OUTPUT': parameters['Resultado']
            }
        else:
            alg_params = {
                'FIELDS': ["'",'ID','DE','RMS','va','Classe_A', 'Classe_B', 'Classe_C', 'Classe_D', 'Quartil2',"'"],
                'INPUT': outputs['Quartil2']['OUTPUT'],
                'OUTPUT': parameters['Resultado']
                
            }
        
        outputs['RetainFields'] = processing.run('native:retainfields', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        results['Resultado'] = outputs['RetainFields']['OUTPUT']

        feedback.setCurrentStep(23)
        if feedback.isCanceled():
            return {}

        # Ajustar estilo para camada vetor
        alg_params = {
            'INPUT': outputs['RetainFields']['OUTPUT'],
            'STYLE': os.path.join(profilepath,'python/plugins/QPEC2/estilo_final.qml')
        }
        outputs['AjustarEstiloParaCamadaVetor'] = processing.run('qgis:setstyleforvectorlayer', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        return results
        
    def name(self):
        
        return 'QPEC'

    def displayName(self):
        return 'Avaliação Planimétrica PEC PCD v 0.1'

    def group(self):
        return None

    def groupId(self):
        return None

    def shortHelpString(self):
        return """<html><body><h2>Descrição do Algoritmo</h2>
<p>Esse complemento realiza a Avaliação da Acurácia Posicional Planimétrica de feições pontuais a partir do método da Especificação Técnica para Controle de Qualidade de Dados Geoespaciais (ET-CQDG), criada em 2016 pela Diretoria do Serviço Geográfico (DSG). A avaliação é feita considerando o Padrão de Exatidão Cartográfica para produtos Cartográficos Digitais (PEC PCD).

Obtem-se as Distâncias Euclidianas (DE) entre as feições avaliadas e as de referência e o Erro Médio Quadrático (EMQ). Verifica-se se 90% das DE são menores que a Classe estabelecida para o PEC PCD e se o EMQ encontrado atende ao Erro Padrão obtido para a mesma Classe. </p>
<h2>Parâmetros de entrada</h2>
<h3>Insira as feições de Referência (Camada 1)</h3>
<p>Entrada dos arquivos vetoriais de Referência (projetado em UTM).</p>
<h3>Atributo da Camada 1</h3>
<p>Selecione o campo coincidente nas feições de referência para união.</p>
<h3>Insira as feições a serem avaliadas (Camada 2)</h3>
<p>Entrada dos arquivos vetoriais a serem avaliados (projetado em UTM).</p>
<h3>Atributo da Camada 2</h3>
<p>Selecione o campo coincidente nas feições de referência para união.</p>
<h3>Insira o denominador de Escala desejado</h3>
<p>Insira o denominador de Escala da qual deseja realizar as análises.</p>
<h3>Exibir resultado para todas as Escalas do MSB</h3>
<p>Caso queira que sejam apresentados os resultados para todas as Escalas do Mapeamento Sistemático Brasileiro (1:1000, 1:2000, 1:5000, 1:10000, 1:25000, 1:50000, 1:100000 e 1250000) selecione esta opção.</p>
<h3>Resultado</h3>
<p></p>
<h2>Saídas</h2>
<h3>Resultado</h3>
<p></p>
<br><p align="right">Autor do algoritmo: Elias Nasr Naim Elias</p><p align="right">Versão do algoritmo: 0.1</p></body></html>"""

    def createInstance(self):
        return ETCQDGAlgorithm()